# beginning student language {#bsl}

## Module
This page provides an overview of the material for the first module of the course including topics, learning goals, estimate of time required and study tips. Each module of the course will start with a similar page which you can always access from the navigation bar to the left.

In this course we use a specially designed programming language called Beginning Student Language (BSL). The BSL language is small and simple, and you will be able to learn most of it in this first module. Its simplicity has two benefits. First it allows us to spend more time on learning the design method which is the real focus of the course. In addition, because BSL forms the core of nearly every other language you will ever use, learning the design method using BSL will help you adapt the material you learn in this course to other programming languages.

### Learning goals
* Be able to write expressions that operate on primitive data including numbers, strings, images and booleans.
* Be able to write constant and function definitions.
* Be able to write out the step-by-step evaluation of simple expressions including function calls.
* Be able to use the stepper to automatically step through the evaluation of an expression.
* Be able to use the Dr Racket help desk to discover new primitives.

## Expressions
Racket *evaluates* expressions to produce valeus
```
(+ 3 4) ;This is an expression
7       ;This is a value
```

To form an expression: 
```
(<primitive> <expression> ...)
```

Here is a problem: Find the missing side of the length triangle via $\sqrt{3^2 + 4^2}$. Write the BSL expression that solves this.
```
(sqrt (+ (sqr 3) (sqr 4)))
```

## Evaluations
We learned how to write expressions that operates on numbers, now we will look at the rules RAckert uses to evaluate those expressions. 

How does Racket evaluate this expressions to produce a value?
```
(+ (* 3 4)(- (+ 1 2) 3)) 
(+ 2 12 (- (+ 1 2) 3)) ;step 1
(+ 2 12 (-  3 3))      ;step 2
(+ 2 12 0)             ;step 3
14                     ;step 4
```

To evaluate a primitive call: 

1. Reduce operands to values
2. Then apply primitive to the valeus
3. Intuitively, we go from left to right and inside to outside